<?php

/**
 * Used to track other files generated by templates
 */
function pkgi_track_instance($path)
{
    $pkgi_root_path = realpath(getenv('APPNAME_HOME'));
    $pkgi_md5_path  = realpath(getenv('APPNAME_HOME').'/.pkgi/lastmd5');
    
    $path      = preg_replace('/^'.preg_quote($pkgi_root_path,'/').'/', '', $path);
    $t_dst     = $pkgi_root_path.$path;
    $t_dst_md5 = $pkgi_md5_path.$path;

    if (is_link($t_dst)) {
        // enregistre les liens symboliques
        @unlink($t_dst_md5);
        @mkdir(dirname($t_dst_md5), 0777, true);
        symlink(readlink($t_dst), $t_dst_md5);
    } else if (is_dir($t_dst)) {
        // enregistre les répertoires
        @mkdir($t_dst_md5, 0777, true);
    } else if (is_file($t_dst)) {
        // enregistre les simples fichiers
        $f_md5 = md5(file_get_contents($t_dst));
        @unlink($t_dst_md5);
        @mkdir(dirname($t_dst_md5), 0777, true);
        file_put_contents($t_dst_md5, $f_md5);
    }
}
