#! /bin/sh
##3.5...10...15...20...25...30...35...40...45...50...55...60...65...70...75...80
## 
##  LSB Startup script for Express / NodeJS
##
##
## Author: Nicolas Thouvenin <nthouvenin@gmail.com>
##

################################################################################
##                                                                            ##
#                        Configuration                                         # 
##                                                                            ##
################################################################################
NODE=`which node`

ROOT_PATH=`dirname $(readlink -f $0)`"/../.."
ROOT_PATH=`readlink -f $ROOT_PATH`

APP_JS=${ROOT_PATH}/var/express/app.js
ERROR_LOG=${ROOT_PATH}/var/log/express/error.log
CONSOLE_LOG=${ROOT_PATH}/var/log/express/console.log

################################################################################
##                                                                            ##
#                         Execution                                            #
##                                                                            ##
################################################################################
touch $ERROR_LOG || { echo "Unable to write $ERROR_LOG"; exit 1; }
exec 2>>$ERROR_LOG

touch $CONSOLE_LOG || { echo "Unable to write $CONSOLE_LOG"; exit 1; }
exec >>$CONSOLE_LOG

[ -x "$NODE" ] || { echo "Unable to exec $NODE" >&2; exit 1; }
[ -f "$APP_JS" ] || { echo "Unable to read $APP_JS" >&2; exit 1; }

echo "Express server launched with pid $$ at "`date`
exec $NODE $APP_JS $*
